# Generated by Django 2.2.19 on 2024-05-30 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(blank=True, default='images2.jpeg', null=True, upload_to='data_photo_car/', verbose_name='Фото1')),
                ('photo2', models.ImageField(blank=True, default='images2.jpeg', null=True, upload_to='data_photo_car/', verbose_name='Фото2')),
                ('photo3', models.ImageField(blank=True, default='images2.jpeg', null=True, upload_to='data_photo_car/', verbose_name='Фото3')),
                ('photo4', models.ImageField(blank=True, default='images2.jpeg', null=True, upload_to='data_photo_car/', verbose_name='Фото4')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('contact', models.CharField(blank=True, max_length=30, null=True)),
                ('dacoin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FuturePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(blank=True, default='images2.jpeg', null=True, upload_to='data_photo_bike/', verbose_name='Фото1')),
                ('photo2', models.ImageField(blank=True, default='images2.jpeg', null=True, upload_to='data_photo_bike/', verbose_name='Фото2')),
                ('photo3', models.ImageField(blank=True, default='images2.jpeg', null=True, upload_to='data_photo_bike/', verbose_name='Фото3')),
                ('photo4', models.ImageField(blank=True, default='images2.jpeg', null=True, upload_to='data_photo_bike/', verbose_name='Фото4')),
            ],
        ),
        migrations.CreateModel(
            name='NowPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(blank=True, default='images2.jpeg', null=True, upload_to='data_photo_bike/', verbose_name='Фото1')),
                ('photo2', models.ImageField(blank=True, default='images2.jpeg', null=True, upload_to='data_photo_bike/', verbose_name='Фото2')),
                ('photo3', models.ImageField(blank=True, default='images2.jpeg', null=True, upload_to='data_photo_bike/', verbose_name='Фото3')),
                ('photo4', models.ImageField(blank=True, default='images2.jpeg', null=True, upload_to='data_photo_bike/', verbose_name='Фото4')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='Описание фото', max_length=400, null=True)),
                ('additional_info', models.TextField(blank=True, default='Доп. информации нет', null=True)),
                ('childphoto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childphoto', to='foto.ChildPhoto', verbose_name='Детские фото')),
                ('futurephoto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='futurephoto', to='foto.ChildPhoto', verbose_name='Фото из будущего')),
                ('nowphoto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nowphoto', to='foto.ChildPhoto', verbose_name='Фото сейчас')),
            ],
        ),
    ]
