# Generated by Django 2.2.19 on 2024-05-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dacoin',
            field=models.IntegerField(default=1),
        ),
    ]
