# Generated by Django 2.2.19 on 2024-05-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foto', '0002_auto_20240530_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='childphoto',
            name='additional_info',
            field=models.TextField(blank=True, default='Доп. информации нет', null=True),
        ),
        migrations.AddField(
            model_name='childphoto',
            name='description',
            field=models.TextField(blank=True, default='Описание фото', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='futurephoto',
            name='additional_info',
            field=models.TextField(blank=True, default='Доп. информации нет', null=True),
        ),
        migrations.AddField(
            model_name='futurephoto',
            name='description',
            field=models.TextField(blank=True, default='Описание фото', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='nowphoto',
            name='additional_info',
            field=models.TextField(blank=True, default='Доп. информации нет', null=True),
        ),
        migrations.AddField(
            model_name='nowphoto',
            name='description',
            field=models.TextField(blank=True, default='Описание фото', max_length=400, null=True),
        ),
        migrations.DeleteModel(
            name='PhotoAlbum',
        ),
    ]
