# Generated by Django 2.2.19 on 2024-05-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foto', '0003_auto_20240531_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childphoto',
            name='photo1',
            field=models.ImageField(blank=True, default='images2.jpeg', null=True, upload_to='data_photo/', verbose_name='Фото1'),
        ),
        migrations.AlterField(
            model_name='childphoto',
            name='photo2',
            field=models.ImageField(blank=True, default='images2.jpeg', null=True, upload_to='data_photo/', verbose_name='Фото2'),
        ),
        migrations.AlterField(
            model_name='childphoto',
            name='photo3',
            field=models.ImageField(blank=True, default='images2.jpeg', null=True, upload_to='data_photo/', verbose_name='Фото3'),
        ),
        migrations.AlterField(
            model_name='childphoto',
            name='photo4',
            field=models.ImageField(blank=True, default='images2.jpeg', null=True, upload_to='data_photo/', verbose_name='Фото4'),
        ),
        migrations.AlterField(
            model_name='futurephoto',
            name='photo1',
            field=models.ImageField(blank=True, default='images2.jpeg', null=True, upload_to='data_photo/', verbose_name='Фото1'),
        ),
        migrations.AlterField(
            model_name='futurephoto',
            name='photo2',
            field=models.ImageField(blank=True, default='images2.jpeg', null=True, upload_to='data_photo/', verbose_name='Фото2'),
        ),
        migrations.AlterField(
            model_name='futurephoto',
            name='photo3',
            field=models.ImageField(blank=True, default='images2.jpeg', null=True, upload_to='data_photo/', verbose_name='Фото3'),
        ),
        migrations.AlterField(
            model_name='futurephoto',
            name='photo4',
            field=models.ImageField(blank=True, default='images2.jpeg', null=True, upload_to='data_photo/', verbose_name='Фото4'),
        ),
        migrations.AlterField(
            model_name='nowphoto',
            name='photo1',
            field=models.ImageField(blank=True, default='images2.jpeg', null=True, upload_to='data_photo/', verbose_name='Фото1'),
        ),
        migrations.AlterField(
            model_name='nowphoto',
            name='photo2',
            field=models.ImageField(blank=True, default='images2.jpeg', null=True, upload_to='data_photo/', verbose_name='Фото2'),
        ),
        migrations.AlterField(
            model_name='nowphoto',
            name='photo3',
            field=models.ImageField(blank=True, default='images2.jpeg', null=True, upload_to='data_photo/', verbose_name='Фото3'),
        ),
        migrations.AlterField(
            model_name='nowphoto',
            name='photo4',
            field=models.ImageField(blank=True, default='images2.jpeg', null=True, upload_to='data_photo/', verbose_name='Фото4'),
        ),
    ]
