# Generated by Django 2.2.19 on 2024-06-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foto', '0005_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otziv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('text', models.TextField()),
            ],
        ),
    ]
