# Generated by Django 2.2.19 on 2024-06-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foto', '0006_otziv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='dacoin',
        ),
        migrations.AddField(
            model_name='client',
            name='dacoin_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='dacoin_clean',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='dacoin_foto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='dacoin_general',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='dacoin_like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='dacoin_otzivi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='dacoin_pay',
            field=models.BooleanField(default=False),
        ),
    ]
