# Generated by Django 2.2.19 on 2024-06-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foto', '0007_auto_20240618_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('like', models.IntegerField(default=0)),
            ],
        ),
    ]
