# Generated by Django 2.2.19 on 2024-06-18 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foto', '0008_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='like',
            new_name='percent',
        ),
    ]
